version: "3.7"

services:
  django:
    build: ./backend
    container_name: dev-django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    volumes:
      - ./backend/:/srv/app
    depends_on:
      - db
  react:
    build: ./frontend
    container_name: dev-react
    command: npm start
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/:/srv/app
    depends_on:
      - django
  db:
    image: postgres:12.0-alpine
    container_name: dev-db
    ports:
      - 5432:5432
    env_file: ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    build: ./nginx
    container_name: dev-nginx
    ports:
      - 80:80
    restart: always
    volumes:
      - ./backend/static:/srv/app/static
      - ./backend/media:/srv/app/media
    depends_on:
      - django
      - react
      - db

volumes:
  postgres_data:
